<a href="https://colab.research.google.com/github/kalehdoo/sandbox/blob/main/P001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy Tutorial

In [6]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5]) 

print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [5]:
print(np.__version__)

1.19.5


In [21]:
ndarray_0dim = np.array(1)
print(ndarray_0dim)
ndarray_1dim = np.array([1,3,2])
print(ndarray_1dim)
ndarray_2dim = np.array([[1,2,3],[1,3,5]])
print(ndarray_2dim)
print(ndarray_2dim[1,2])
ndarray_3dim = np.array(
    [
     [
     [1,3,4],[1,4,6]
     ],
     [
      [1,3,5],[1,6,7]
     ]
    ]
     
)
print(ndarray_3dim)
print(ndarray_3dim.ndim)

1
[1 3 2]
[[1 2 3]
 [1 3 5]]
5
[[[1 3 4]
  [1 4 6]]

 [[1 3 5]
  [1 6 7]]]
3


In [20]:
create_array = np.array([1,6,2], ndmin=5)
print(create_array)

[[[[[1 6 2]]]]]
