In [1]:
import torch

#x=torch.rand(5,3)
x = torch.Tensor([2,5])
y = torch.Tensor([3,6])

print(x*y)

x=torch.zeros([3,4])

tensor([ 6., 30.])


In [3]:
x=torch.zeros([5,6])
x

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [5]:
x.shape

torch.Size([5, 6])

In [7]:
y = torch.rand([2,5])
y

tensor([[0.9574, 0.3102, 0.9639, 0.9303, 0.1362],
        [0.8131, 0.0887, 0.0088, 0.2496, 0.6713]])

In [8]:
y.view([1,10])

tensor([[0.9574, 0.3102, 0.9639, 0.9303, 0.1362, 0.8131, 0.0887, 0.0088, 0.2496,
         0.6713]])